import {test,expect} from 'bun:test';
import {createLiveApi,projectListing} from '../src/server/live';
const request=(body:unknown,origin='http://localhost')=>new Request('http://localhost/api/live/search',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)});
test('opening status never calls provider or reserves spend',async()=>{let calls=0;const api=createLiveApi({key:()=> 'secret',fetch:(async()=>{calls++;throw Error();}) as unknown as typeof fetch,reserve:()=>{calls++;},budget:()=>({limitPence:1000,reservedPence:0,remainingPence:1000})});expect((await api(new Request('http://localhost/api/live/status'))).status).toBe(200);expect(calls).toBe(0);expect((await api(request({make:'Porsche',model:'911'},'https://evil.example'))).status).toBe(403);expect(calls).toBe(0);});
test('reserve happens before a single request; failures never retry or leak keys',async()=>{const events:string[]=[];const api=createLiveApi({key:()=> 'secret-key',reserve:()=>{events.push('reserve');},budget:()=>({limitPence:1000,reservedPence:2,remainingPence:998}),fetch:(async()=>{events.push('fetch');throw Error('secret-key');}) as unknown as typeof fetch});const r=await api(request({make:'Porsche',model:'911'}));expect(events).toEqual(['reserve','fetch']);expect(await r.text()).not.toContain('secret-key');});
test('exhausted budget blocks outbound request',async()=>{let calls=0;const api=createLiveApi({key:()=> 'secret',reserve:()=>{throw Error();},budget:()=>({limitPence:1000,reservedPence:1000,remainingPence:0}),fetch:(async()=>{calls++;throw Error();}) as unknown as typeof fetch});expect((await api(request({make:'Porsche',model:'911'}))).status).toBe(503);expect(calls).toBe(0);});
test('projection preserves unknowns and excludes keys, registrations and cached images',()=>{const car=projectListing({id:'abc',vehicle_registration_mark:'PRIVATE',build:{make:'Porsche'},vdp_url:'javascript:alert(1)',media:{photo_links:['https://api.marketcheck.com/image?api_key=secret']}});expect(car.price).toBeNull();expect(car.url).toBeNull();expect(car.photo).toBeNull();expect(JSON.stringify(car)).not.toContain('PRIVATE');});
test('range and exact derivative parameters share one budgeted call',async()=>{
 let calls=0;let reserved=0;let query=new URLSearchParams();
 const api=createLiveApi({key:()=> 'secret',reserve:()=>{reserved++;},budget:()=>({limitPence:1000,reservedPence:2,remainingPence:998}),fetch:(async(u:any)=>{calls++;query=new URL(u).searchParams;return Response.json({listings:[],num_found:0,facets:{variant:[{item:'Carrera Gts Semi-auto',count:4},{message:'unsupported'}]}});}) as unknown as typeof fetch});
 const r=await api(request({make:'Porsche',model:'911',minYear:'2015',maxYear:'2022',maxPrice:'80000',maxMileage:'40000',derivative:'Carrera Gts Semi-auto',page:1}));
 expect(r.status).toBe(200);expect(query.get('year_range')).toBe('2015-2022');expect(query.get('price_range')).toBe('0-80000');expect(query.get('miles_range')).toBe('0-40000');expect(query.get('variant')).toBe('Carrera Gts Semi-auto');expect(query.get('start')).toBe('10');expect(calls).toBe(1);expect(reserved).toBe(1);expect((await r.json()).derivatives).toEqual([{value:'Carrera Gts Semi-auto',count:4}]);
});
test('invalid bounds fail before spending',async()=>{
 let spend=0;const api=createLiveApi({key:()=> 'secret',reserve:()=>{spend++;},budget:()=>({limitPence:1000,reservedPence:0,remainingPence:1000}),fetch:(async()=>{throw Error('Must not fetch');}) as unknown as typeof fetch});
 for(const invalid of [{minYear:'2020',maxYear:'2010'},{maxMileage:'-5'},{maxPrice:'1e4'},{minYear:'1899'},{derivative:'GTS,,GT3'}])expect((await api(request({make:'Porsche',model:'911',...invalid}))).status).toBe(400);
 expect(spend).toBe(0);
});

test('derivative family is passed as exact comma-separated variants in one call',async()=>{let calls=0;let variant='';const api=createLiveApi({key:()=> 'secret',reserve:()=>{},budget:()=>({limitPence:1000,reservedPence:2,remainingPence:998}),fetch:(async(u:any)=>{calls++;variant=new URL(u).searchParams.get('variant')!;return Response.json({listings:[],num_found:0});}) as unknown as typeof fetch});expect((await api(request({make:'Porsche',model:'911',derivative:'Carrera Gts Semi-auto,Targa 4 Gts Manual'}))).status).toBe(200);expect(calls).toBe(1);expect(variant).toBe('Carrera Gts Semi-auto,Targa 4 Gts Manual');});
