import {useState} from 'react';
import type {VehicleDetail,BuyingReport} from '../shared/report';
import {HistoryView} from './HistoryView';
export {buildTimeline} from '../shared/history';
import {dateLabel} from '../shared/history';
type Mot=NonNullable<BuyingReport['evidence']>['mot'];
export function VehiclePortrait({detail,name}:{detail:VehicleDetail;name:string}){
 const [failed,setFailed]=useState(false);
 const available=detail.image&&!failed&&(!detail.image.expires||Date.parse(detail.image.expires)>Date.now())&&(detail.image.url.startsWith('https://vehicleimages.ukvehicledata.co.uk/'));
 return <figure className="vehicle-portrait">{available?<img src={detail.image!.url} alt={detail.image?.source==='dealer'?`Dealer-advertised photograph of ${name}`:`Supplier illustration of ${name}; not a verified photograph of this vehicle`} referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<div className="portrait-placeholder"><span>THE DRIVER’S CAR</span><strong>{name}</strong><p>Supplier image unavailable</p></div>}<figcaption>{detail.image?.source==='dealer'?'Photograph from the Porsche Centre advert · condition not independently verified':'Supplier model image · not a verified photograph of this car'}</figcaption></figure>;
}
export function VehicleFacts({detail}:{detail:VehicleDetail}){
 const stats=[detail.powerBhp!=null?{value:Math.round(detail.powerBhp),unit:'bhp',label:'Power'}:null,detail.zeroToSixty!=null?{value:detail.zeroToSixty,unit:'sec',label:'0–60 mph'}:detail.zeroToHundred!=null?{value:detail.zeroToHundred,unit:'sec',label:'0–100 km/h'}:null,detail.torqueNm!=null?{value:detail.torqueNm,unit:'Nm',label:'Torque'}:null,detail.topSpeedMph!=null?{value:detail.topSpeedMph,unit:'mph',label:'Model top speed'}:null].filter(x=>x!==null);
 return <div className="vehicle-story">
 {stats.length>0&&<section className="character data-card"><p className="eyebrow">Model specifications</p><h2>{detail.engine}</h2><p className="section-intro">{detail.transmission}. {detail.seats} seats. The key model specifications, with the detail kept in context.</p><div className="performance-strip">{stats.map(s=><div key={s.label}><strong>{s.value}<small>{s.unit}</small></strong><span>{s.label}</span></div>)}</div><p className="small-note">Supplier model figures, not measured performance of this vehicle.</p></section>}
 <section className="vehicle-profile-card data-card"><div className="profile-identity"><p className="eyebrow">Identity & appearance</p><h2>Vehicle profile</h2><dl><div><dt>First registered</dt><dd>{dateLabel(detail.registered)}</dd></div><div><dt>Current colour</dt><dd>{detail.colour??'Not supplied'}</dd></div><div><dt>Original colour</dt><dd>{detail.originalColour??'Not supplied'}</dd></div></dl><p className="small-note">{detail.colourChanges===0?'No recorded colour changes. This does not establish original paintwork.':detail.colourChanges!=null?`${detail.colourChanges} colour changes recorded.`:'Colour change history unavailable.'}</p></div>
 <div className="profile-dimensions"><p className="eyebrow">Size & practicality</p><h2>Size and everyday practicality</h2>{detail.dimensions&&<><svg viewBox="0 0 400 170" role="img" aria-label="Schematic car outline; not to scale"><path d="M40 113 L55 85 L130 77 L174 44 L262 44 L300 80 L349 94 L363 117 L325 117 A23 23 0 0 0 279 117 L127 117 A23 23 0 0 0 81 117 Z" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="104" cy="118" r="17" fill="none" stroke="currentColor" strokeWidth="2"/><circle cx="302" cy="118" r="17" fill="none" stroke="currentColor" strokeWidth="2"/><path d="M40 153 H363 M40 146 V160 M363 146 V160 M377 44 V135 M371 44 H384 M371 135 H384" stroke="currentColor" opacity=".5"/></svg><div className="dimension-values"><div><strong>{(detail.dimensions.length/1000).toFixed(2)} m</strong><span>Length</span></div><div><strong>{(detail.dimensions.width/1000).toFixed(2)} m</strong><span>Width*</span></div><div><strong>{(detail.dimensions.height/1000).toFixed(2)} m</strong><span>Height</span></div></div><p className="small-note">Schematic, not to scale. *Mirror inclusion is not specified. Allow additional clearance for doors and access when checking a garage.</p></>}{!detail.dimensions&&<p className="empty-data">Dimensions unavailable in the supplied data.</p>}{detail.weight&&<details className="weight-details"><summary>Weight figures explained</summary><p className="small-note">Supplier kerb weight: {detail.weight.kerb.toLocaleString('en-GB')} kg. DVLA mass in service: {detail.weight.massInService.toLocaleString('en-GB')} kg. These are different definitions.</p></details>}</div></section></div>;
}
export function VehicleStory({detail,mot,events=[]}:{detail:VehicleDetail;mot:Mot;events?:BuyingReport['historyEvents']}){
 return <><VehicleFacts detail={detail}/><HistoryView detail={detail} mot={mot} events={events}/></>;
}
