import { useEffect, useState } from 'react';
import type { Car, SearchResult, DetailResult } from '../shared/types';
import { CarArt } from './CarArt';
import { BrandMark } from './BrandMark';
import { Detail, money, number, shortDate } from './Detail';
import { useLocalList, isId, isSaved } from './storage';

const defaults = { q:'', make:'', maxPrice:'', maxMileage:'', features:'', sort:'recent' };
type Filters = typeof defaults;
function readFilters(): Filters { const p=new URLSearchParams(location.search); return Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,p.get(k)??v])) as Filters; }
function queryFor(f: Filters) {return new URLSearchParams(Object.entries(f).filter(([,v])=>v)).toString();}
function currentId() {return location.pathname.startsWith('/cars/')?location.pathname.slice(6):null;}
async function getJson<T>(path: string,signal:AbortSignal): Promise<T> {
  const r=await fetch(path,{signal});const body=await r.json(); if(!r.ok)throw new Error(body.error??'Could not load local data.');return body;
}
export function App() {
  const [filters,setFilters]=useState<Filters>(readFilters);
  const [id,setId]=useState<string|null>(currentId);
  const [view,setView]=useState<'discover'|'watchlist'|'alerts'>('discover');
  const [result,setResult]=useState<SearchResult|null>(null);
  const [detail,setDetail]=useState<DetailResult|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [retry,setRetry]=useState(0);
  const [notice,setNotice]=useState('');
  const [watched,saveWatched,watchError]=useLocalList('carscope:watches:v1',isId);
  const [saved,saveSearches,saveError]=useLocalList('carscope:searches:v1',isSaved);
  useEffect(()=>{const fn=()=>{setId(currentId());setFilters(readFilters());setView('discover');};window.addEventListener('popstate',fn);return()=>window.removeEventListener('popstate',fn);},[]);
  useEffect(()=>{
    const controller=new AbortController();setLoading(true);setError('');
    const timer=setTimeout(async()=>{
      try {
        if(id){setDetail(await getJson<DetailResult>(`/api/cars/${encodeURIComponent(id)}`,controller.signal));}
        else {setResult(await getJson<SearchResult>(`/api/cars?${view==='watchlist'?'':queryFor(filters)}`,controller.signal));}
        setLoading(false);
      }catch(e){if(controller.signal.aborted)return;setError(e instanceof Error?e.message:'Could not load local data.');setLoading(false);}
    },150);
    return()=>{clearTimeout(timer);controller.abort();};
  },[id,filters,view,retry]);
  function change(next: Filters){setFilters(next);history.replaceState(null,'',`/?${queryFor(next)}`);}
  function open(carId:string){history.pushState(null,'',`/cars/${carId}?${queryFor(filters)}`);setId(carId);window.scrollTo(0,0);}
  function navigate(next:typeof view){setId(null);setView(next);history.pushState(null,'',`/?${queryFor(filters)}`);window.scrollTo(0,0);}
  function toggle(carId:string){saveWatched(watched.includes(carId)?watched.filter(w=>w!==carId):[...watched,carId]);}
  function saveSearch(){const query=queryFor(filters);if(saved.some(s=>s.query===query)){setNotice('This search is already saved. Open Search alerts to manage it.');return;}saveSearches([...saved,{id:crypto.randomUUID(),name:[filters.make,filters.q].filter(Boolean).join(' ')||'All enthusiast cars',query}]);setNotice('Search saved in this browser. Alert delivery is a prototype stub.');}
  const cars=result?.cars.filter(c=>view!=='watchlist'||watched.includes(c.id))??[];
  const source=id?detail?.source:result?.source;
  const asOf=id?detail?.asOf:result?.asOf;
  return <><a className="skip-link" href="#main">Skip to content</a><header className="topbar"><a className="brand" href="/" onClick={e=>{e.preventDefault();navigate('discover');}} aria-label="CarScope home"><BrandMark/><span className="brand-wordmark">Car<span>Scope</span></span><span className="beta">V1</span></a><nav aria-label="Main navigation"><button aria-current={view==='discover'&&!id?'page':undefined} onClick={()=>navigate('discover')}>Discover</button><button aria-current={view==='watchlist'&&!id?'page':undefined} onClick={()=>navigate('watchlist')}>Watchlist <span className="count">{watched.length}</span></button><button aria-current={view==='alerts'&&!id?'page':undefined} onClick={()=>navigate('alerts')}>Search alerts <span className="count">{saved.length}</span></button></nav><span className="local-badge"><i/> Offline prototype</span></header>
    <div className="data-strip"><span><i/> {source==='imported'?'IMPORTED SNAPSHOT':'FICTIONAL DEMO DATA'} <b>·</b> {asOf?shortDate(asOf):'Local dataset'}</span><span>Live API access disabled · £0 API spend</span></div>
    {(notice||watchError||saveError)&&<div className="notice" role="status">{watchError||saveError||notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}>×</button></div>}
    {id ? (loading?<main id="main" className="loading" role="status">Opening the garage…</main>:error?<ErrorState error={error} retry={()=>setRetry(retry+1)} back={()=>navigate('discover')}/>:detail&&<Detail data={detail} watched={watched.includes(id)} toggle={()=>toggle(id)} open={open} back={()=>navigate('discover')}/>) : view==='alerts' ? <main id="main" className="saved-page"><p className="eyebrow">YOUR NEXT CAR, ON YOUR TERMS</p><h1>Search alerts<span className="accent">.</span></h1><p className="intro">Keep your criteria close. Live monitoring comes later.</p><div className="stub-note"><strong>Saved locally · Alerts inactive</strong><p>These are UI stubs. No background searches, emails or notifications are sent. Open a search to check the current local dataset.</p></div>{saved.length?saved.map(s=><article className="saved-item" key={s.id}><div><p className="eyebrow">SAVED SEARCH / DELIVERY INACTIVE</p><h2>{s.name}</h2><p>{describeQuery(s.query)}</p></div><div className="saved-actions"><button className="button" onClick={()=>{const params=new URLSearchParams(s.query);const next=Object.fromEntries(Object.entries(defaults).map(([k,v])=>[k,params.get(k)??v])) as Filters;setFilters(next);setView('discover');history.pushState(null,'',`/?${s.query}`);}}>Open search ↗</button><button className="text-button" onClick={()=>saveSearches(saved.filter(x=>x.id!==s.id))}>Remove</button></div></article>):<Empty title="A good search is worth keeping." body="Set your criteria in Discover, then save the search here." action="Explore cars" onClick={()=>navigate('discover')}/>}</main> : <main id="main"><section className="hero"><div><p className="eyebrow">THE PRESTIGE COLLECTION</p><h1>{view==='watchlist'?<>Your shortlist<span className="accent">.</span></>:<>Exceptional cars.<br/><em>Considered choices.</em></>}</h1><p className="intro">{view==='watchlist'?'The cars you’re keeping an eye on. Saved in this browser.':'Discover remarkable marques. Compare the details. Find the car worth pursuing.'}</p></div><div className="hero-side"><span className="edition">CURATED BY CURIOSITY</span><p>The right marque.<br/>The <em>rare detail.</em></p><span>EXPLORE THE COLLECTION ↙</span></div></section>
    <div className={`workspace ${view==='watchlist'?'watch-workspace':''}`}>{view==='discover'&&<aside className="filters"><div className="filter-title"><h2>Your criteria</h2><button className="text-button" onClick={()=>change({...defaults})}>Reset</button></div><label>MAKE<select value={filters.make} onChange={e=>change({...filters,make:e.target.value})}><option value="">All makes</option>{result?.makes.map(m=><option key={m}>{m}</option>)}</select></label><label>MAXIMUM PRICE<select value={filters.maxPrice} onChange={e=>change({...filters,maxPrice:e.target.value})}><option value="">Any budget</option>{[25000,35000,50000,65000,70000,75000,100000].map(n=><option key={n} value={n}>{money(n)}</option>)}{filters.maxPrice&&!['25000','35000','50000','65000','70000','75000','100000'].includes(filters.maxPrice)&&<option value={filters.maxPrice}>{filters.maxPrice}</option>}</select></label><label>MAXIMUM MILEAGE<select value={filters.maxMileage} onChange={e=>change({...filters,maxMileage:e.target.value})}><option value="">Any mileage</option>{[15000,20000,30000,40000,50000].map(n=><option key={n} value={n}>{number(n)} miles</option>)}{filters.maxMileage&&!['15000','20000','30000','40000','50000'].includes(filters.maxMileage)&&<option value={filters.maxMileage}>{filters.maxMileage}</option>}</select></label><fieldset><legend>MUST-HAVES</legend>{['Air conditioning','Carbon seats','Full service history'].map(f=><label className="checkbox" key={f}><input type="checkbox" checked={filters.features.split(',').includes(f)} onChange={e=>change({...filters,features:(e.target.checked?[...filters.features.split(',').filter(Boolean),f]:filters.features.split(',').filter(x=>x!==f)).join(',')})}/>{f}</label>)}</fieldset><div className="filter-note"><span>↗</span><p>The right spec matters.<br/><small>Search model, trim or feature to find your kind of car.</small></p></div></aside>}
    <section className="results" aria-label="Car results">{view==='discover'&&<><form className="search-box" onSubmit={e=>e.preventDefault()}><span aria-hidden="true">⌕</span><input aria-label="Search model, trim or feature" placeholder="Try ‘Lotus Exige 410’ or ‘manual’" value={filters.q} onChange={e=>change({...filters,q:e.target.value})}/><kbd>SEARCH</kbd></form><div className="quick-searches"><span>Explore a marque</span>{['Porsche','Ferrari','Lotus'].map(q=><button key={q} onClick={()=>change({...defaults,q})}>{q} ↗</button>)}</div></>}
    <div className="results-heading"><h2>{loading?'Searching…':`${cars.length} ${view==='watchlist'?'watched cars':'cars in the collection'}`}</h2>{view==='discover'&&<div className="result-actions"><label className="sort-label">Sort by<select aria-label="Sort results" value={filters.sort} onChange={e=>change({...filters,sort:e.target.value})}><option value="recent">Newest listed</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option><option value="mileage">Lowest mileage</option><option value="days">Longest listed</option></select></label><button className="save-search" onClick={saveSearch}>＋ Save search</button></div>}</div>
    {loading?<div className="loading" role="status">Finding the interesting ones…</div>:error?<ErrorState error={error} retry={()=>setRetry(retry+1)}/>:cars.length?<div className="car-grid">{cars.map(car=><CarCard key={car.id} car={car} watched={watched.includes(car.id)} toggle={()=>toggle(car.id)} open={()=>open(car.id)}/>)}</div>:<Empty title={view==='watchlist'?'Your garage starts here.':'Nothing in this corner of the garage.'} body={view==='watchlist'?'Use the watch button on a car to add it to your shortlist.':'Try a broader search or remove a filter. This prototype has a small local dataset.'} action={view==='watchlist'?'Explore cars':'Clear filters'} onClick={()=>{change({...defaults});navigate('discover');}}/>}
    </section></div></main>}
    <footer><a className="brand" href="/"><BrandMark/><span className="brand-wordmark">Car<span>Scope</span></span><span className="beta">V1</span></a><p>Built for the drive, before the drive.</p><span>Local prototype · No live listings or alert delivery</span></footer></>;
}
function CarCard({car,watched,toggle,open}:{car:Car;watched:boolean;toggle:()=>void;open:()=>void}) {
  const drop=car.history[0]!.price-car.price;
  return <article className="car-card"><div className="card-visual"><a href={`/cars/${car.id}`} onClick={e=>{e.preventDefault();open();}} aria-label={`View ${car.make} ${car.model} ${car.trim}`}><CarArt car={car}/></a><button className={`watch-button ${watched?'active':''}`} aria-label={`${watched?'Unwatch':'Watch'} ${car.make} ${car.model} ${car.trim}`} aria-pressed={watched} onClick={toggle}><svg className="wishlist-icon" viewBox="0 0 24 24" fill="none" aria-hidden="true" focusable="false"><path d="M7 3.75h10a1.25 1.25 0 0 1 1.25 1.25v15l-6.25-4-6.25 4V5A1.25 1.25 0 0 1 7 3.75Z" stroke="currentColor" strokeWidth="1.65" strokeLinejoin="round"/></svg></button>{drop>0&&<span className="price-drop">↓ {money(drop)} PRICE DROP</span>}</div><div className="card-content"><p className="card-meta">{car.year} <span>·</span> {car.transmission} <span>·</span> {car.location}</p><h3><a href={`/cars/${car.id}`} onClick={e=>{e.preventDefault();open();}}>{car.make} {car.model}<span>{car.trim}</span></a></h3><div className="card-price"><strong>{money(car.price)}</strong><span>{number(car.mileage)} miles</span></div><div className="card-bottom"><span>{car.daysOnMarket} days on market</span><button className="text-button" aria-label={`Explore ${car.make} ${car.model} ${car.trim}`} onClick={open}>Explore ↗</button></div></div></article>;
}
function Empty({title,body,action,onClick}:{title:string;body:string;action:string;onClick:()=>void}){return <div className="empty"><span>↗</span><h2>{title}</h2><p>{body}</p><button className="button" onClick={onClick}>{action}</button></div>;}
function ErrorState({error,retry,back}:{error:string;retry:()=>void;back?:()=>void}){return <section id="main" className="empty" role="alert"><h2>Couldn’t load this view.</h2><p>{error}</p><button className="button" onClick={retry}>Try again</button>{back&&<button className="text-button" onClick={back}>Back to search</button>}</section>;}
function describeQuery(query:string){const p=new URLSearchParams(query);return [p.get('q'),p.get('make'),p.get('maxPrice')?`Up to ${money(Number(p.get('maxPrice')))}`:'Any budget',p.get('maxMileage')?`Under ${number(Number(p.get('maxMileage')))} miles`:'Any mileage',p.get('features')].filter(Boolean).join(' · ');}
