import type {ReactNode} from 'react';
import type {DetailData} from '../shared/detail';
import {equipmentSections,equipmentHighlights} from '../shared/detail';
import type {EquipmentPreference} from '../shared/preferences';
import {SpecificationMatch} from './SpecificationMatch';
const money=(n:number|null)=>n===null?'Price unavailable':new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
const date=(s:string)=>new Date(`${s}T12:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
export function CarDetailPage({data,photo,action,preferences=[],onEdit,back,open,busy=false,error}:{data:DetailData;photo:ReactNode;action?:ReactNode;preferences?:EquipmentPreference[];onEdit?:()=>void;back:()=>void;open:(id:string)=>void;busy?:boolean;error?:string}){
 const {car,comparables}=data;const equipment=equipmentSections(car.features,car.options);const highlights=equipmentHighlights(car.features,car.options);
 const priced=comparables.filter(c=>c.price!==null);const average=priced.length?Math.round(priced.reduce((sum,c)=>sum+c.price!,0)/priced.length):null;
 const reference=data.limitedHistory?car.referencePrice:car.history[0]?.price;
 const delta=reference!=null&&car.price!==null?car.price-reference:null;
 const points=car.history;const min=Math.min(...points.map(p=>p.price))-500,max=Math.max(...points.map(p=>p.price))+500;
 const start=points.length?Date.parse(points[0]!.date):0,end=points.length?Date.parse(points[points.length-1]!.date):0;
 const xy=points.map(p=>[24+(Date.parse(p.date)-start)/Math.max(end-start,1)*552,125-(p.price-min)/(max-min)*95]);
 return <main id="main" className="detail-page unified-detail">
  <button className="text-button back" onClick={back}>← Back to results · no request</button>
  {error&&<p className="notice" role="alert">{error}</p>}
  <div className="detail-heading"><div><p className="eyebrow">{car.year??'Year unknown'} / {car.transmission||'Transmission unknown'} / {car.location||'Location unknown'}</p><h1>{car.make} {car.model}<span>{car.trim}</span></h1></div>{action}</div>
  <div className="detail-grid"><section><div className="detail-photo">{photo}</div><SpecificationMatch car={car} fictional={data.source==='fictional'} liveEvidence={data.source==='imported'?undefined:{features:car.features,options:car.options,description:car.description}} preferences={preferences} onEdit={onEdit}/></section>
  <aside className="price-panel"><p className="eyebrow">ASKING PRICE</p><p className="big-price">{money(car.price)}</p>{delta!==null&&<p className="change">{delta<0?'↓ ':delta>0?'↑ ':''}{delta===0?'Unchanged':money(Math.abs(delta))}{delta===0?' from':' since'} {data.limitedHistory?'previous reference price':'first recorded price'}</p>}<dl><div><dt>Mileage</dt><dd>{car.mileage===null?'Not supplied':`${car.mileage.toLocaleString('en-GB')} miles`}</dd></div><div><dt>Days on market</dt><dd>{car.daysOnMarket===null?'Not supplied':`${car.daysOnMarket} days`}</dd></div><div><dt>Transmission</dt><dd>{car.transmission||'Not supplied'}</dd></div><div><dt>Last observed</dt><dd>{data.asOf?date(data.asOf):'Date not supplied'}</dd></div></dl><div className="insight"><span className="eyebrow">COMPARABLE ASKING PRICES</span><p>{average!==null?`${money(average)} average across ${priced.length} same-model listings.`:'No priced same-model comparisons available.'}</p><small>{data.comparisonScope}. Trim, age and condition may differ. This is not a valuation.</small></div><p className="muted small">Seller: {car.seller||'Not supplied'}</p>{car.url&&<a className="button dark" href={car.url} target="_blank" rel="noreferrer">View seller advert ↗</a>}</aside></div>
  <section className="equipment-section"><div className="section-heading"><h2>Specification highlights</h2><span>From the advert</span></div><div className="feature-tags">{highlights.map(h=><span key={h.text}>{h.text}{h.option?' · listed option':''}</span>)}</div>{!highlights.length&&<p className="muted">{equipment.options.length||equipment.other.length?'See the full advertised equipment below.':'No equipment list supplied.'}</p>}<p className="muted small">Advertised equipment, not a verified factory specification. Options listed may need fitment confirmation.</p><div className="equipment-disclosures"><details><summary>Options listed in the advert <span>{equipment.options.length}</span></summary>{equipment.options.length?<ul>{equipment.options.map(f=><li key={f}>{f}</li>)}</ul>:<p>No separate options list supplied.</p>}</details><details><summary>Other advertised equipment <span>{equipment.other.length}</span></summary><p className="muted small">The source does not reliably distinguish standard equipment from extras.</p>{equipment.other.length?<ul>{equipment.other.map(f=><li key={f}>{f}</li>)}</ul>:<p>No other equipment supplied.</p>}</details></div></section>
  <div className="detail-lower"><section className="history"><div className="section-heading"><h2>Price history</h2><span>Asking prices · GBP</span></div>{points.length>1&&end>start&&<svg viewBox="0 0 600 155" role="img" aria-label="Recorded asking price observations; exact dates and prices below"><path d="M24 40H576 M24 85H576 M24 130H576" stroke="#48565e" fill="none"/>{!data.limitedHistory&&<polyline points={xy.map(p=>p.join(',')).join(' ')} fill="none" stroke="currentColor" strokeWidth="2"/>}{xy.map(([cx,cy],i)=><circle key={i} cx={cx} cy={cy} r="5" fill="currentColor"/>)}</svg>}{points.length?<ol className="history-list">{points.map((p,i)=><li key={i}><span>{date(p.date)}<small>{p.label}</small></span><strong>{money(p.price)}</strong></li>)}</ol>:<p className="empty-inline">No dated price observations supplied.</p>}{data.limitedHistory&&car.referencePrice!=null&&!car.referenceDate&&<p className="muted small">Previous reference price: {money(car.referencePrice)} · date not supplied.</p>}<p className="muted small">{data.limitedHistory?'Only supplied reference and latest observations are shown, not a complete price history.':'Recorded asking prices in this dataset.'} No sale prices are inferred.</p></section>
  <section><div className="section-heading"><h2>Compare the market</h2><span>{comparables.length} comparisons</span></div>{comparables.length?comparables.map(c=><button className="comparable" key={c.id} disabled={busy} onClick={()=>open(c.id)}><span><strong>{c.make} {c.model} {c.trim}</strong><small>{c.year??'Year unknown'} · {c.mileage?.toLocaleString('en-GB')??'Unknown'} miles{data.source==='live'?' · Open details: reserve 2p':''}</small></span><b>{money(c.price)} ↗</b></button>):<p className="empty-inline">No other same-model cars in {data.comparisonScope.toLowerCase()}.</p>}<p className="muted small">{data.comparisonScope} · Up to four same-model cars, nearest mileage where supplied. {data.source==='fictional'?'All values are fictional.':data.source==='live'?'No extra search was made.':'Availability is not checked live.'}</p></section></div>
  <details className="seller-description"><summary>Read seller description</summary><p>{car.description||'No seller description supplied.'}</p></details>
 </main>;
}
