import {PreferenceEditor} from './PreferenceEditor';
import type {EquipmentPreference} from '../shared/preferences';
import {useEffect,useRef,useState} from 'react';
import {searchModels,searchDerivatives,LIVE_PAGE_SIZE} from '../shared/search-catalogue';
import {CarDetailPage} from './CarDetailPage';
import {liveDetailData} from '../shared/detail';
import {catalogueMakes} from '../shared/catalogue';
import type {Listing} from '../shared/listing';
type Criteria={make:string;model:string;transmission:string;derivative:string;minYear:string;maxYear:string;maxPrice:string;maxMileage:string};
const pounds=(n:number|null)=>n===null?'Price unavailable':new Intl.NumberFormat('en-GB',{style:'currency',currency:'GBP',maximumFractionDigits:0}).format(n);
export function LivePreview(){
 const [criteria,setCriteria]=useState<Criteria>({make:'Porsche',model:'911',transmission:'',derivative:'',minYear:'',maxYear:'',maxPrice:'',maxMileage:''});
 const [preferences,setPreferences]=useState<EquipmentPreference[]>([]);
 const [submitted,setSubmitted]=useState<Criteria|null>(null);
 const [cars,setCars]=useState<Listing[]>([]);const [detail,setDetail]=useState<Listing|null>(null);
 const [page,setPage]=useState(0);const [total,setTotal]=useState<number|null>(null);
 const [remaining,setRemaining]=useState<number|null>(null);const [ready,setReady]=useState(false);
 const [busy,setBusy]=useState(false);const lock=useRef(false);const [error,setError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/live/status',{cache:'no-store'}).then(r=>r.json()).then(d=>{if(active){setReady(d.ready??false);setRemaining(d.budget?.remainingPence??null);setError(d.error??'');}}).catch(()=>{if(active)setError('Could not read local budget.');});return()=>{active=false;};},[]);
 async function run(kind:'search'|'detail',payload:Record<string,unknown>){
  if(lock.current)return;lock.current=true;setBusy(true);setError('');
  try{const r=await fetch(`/api/live/${kind}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'});const d=await r.json();if(d.budget)setRemaining(d.budget.remainingPence);else {const status=await fetch('/api/live/status',{cache:'no-store'}).then(r=>r.json());setRemaining(status.budget?.remainingPence??null);}if(!r.ok)throw Error(d.error??'Request failed.');if(kind==='search'){setCars(d.cars);setTotal(d.total);setPage(d.page);setSubmitted(Object.fromEntries(Object.keys(criteria).map(k=>[k,String(payload[k]??'')])) as Criteria);setDetail(null);}else setDetail(d.car);
  }catch(e){setError(e instanceof Error?e.message:'Request failed; do not retry without checking usage.');}finally{setBusy(false);lock.current=false;}
 }
 const groups=searchDerivatives(criteria.make,criteria.model);
 const selectedGroup=groups.find(g=>g.variants.join(',')===criteria.derivative);
 const family=selectedGroup?.label??(criteria.derivative?'custom':'');
 const disabled=busy||!ready||remaining===null||remaining<2;
 if(detail)return <CarDetailPage data={liveDetailData(detail,cars)} photo={<LivePhoto key={detail.id} car={detail}/>} preferences={preferences} onEdit={()=>{setDetail(null);requestAnimationFrame(()=>document.getElementById('search-preferences')?.scrollIntoView({block:'center'}));}} back={()=>setDetail(null)} open={id=>void run('detail',{id})} busy={disabled} error={error} action={<span className="detail-allowance">{remaining===null?'Allowance unavailable':`£${(remaining/100).toFixed(2)} allowance remaining`}</span>}/>;
 return <main id="main" className="live-preview integrated-live"><section className="hero"><div><p className="eyebrow">THE ENTHUSIAST COLLECTION</p><h1>Exceptional cars.<br/><em>Considered choices.</em></h1><p className="intro">Explore real cars. Compare the details. Find the one worth pursuing.</p></div><div className="hero-side"><span className="edition">LIVE INVENTORY</span><p>The right marque.<br/>The <em>rare detail.</em></p><span>YOUR SEARCH, ON YOUR TERMS ↙</span></div></section><div className="live-workspace"><aside className="live-criteria"><div className="filter-title"><h2>Your criteria</h2><button className="text-button" disabled={busy} onClick={()=>{setCriteria({make:'Porsche',model:'911',transmission:'',derivative:'',minYear:'',maxYear:'',maxPrice:'',maxMileage:''});setPreferences([]);}}>Reset</button></div><div className="live-budget" role="status"><strong>{remaining===null?'Checking budget…':`£${(remaining/100).toFixed(2)} local allowance remaining`}</strong><span>2p reserved per search or detail · Images use dealer links · No automatic refresh</span></div>{!ready&&remaining!==null&&<p role="alert">Live access is unavailable. Check the server API key.</p>}
 <form className="live-search" onSubmit={e=>{e.preventDefault();void run('search',{...criteria,derivative:criteria.derivative.trim(),page:0});}}><label>Make<select value={criteria.make} onChange={e=>{setCriteria({...criteria,make:e.target.value,model:'',derivative:''});}}>{catalogueMakes.map(m=><option key={m}>{m}</option>)}</select></label><label>Model<input list="live-models" required maxLength={80} value={criteria.model} placeholder="e.g. 911" onChange={e=>{setCriteria({...criteria,model:e.target.value,derivative:''});}}/><datalist id="live-models">{searchModels(criteria.make).map(m=><option key={m} value={m}/>)}</datalist></label><label>Transmission<select value={criteria.transmission} onChange={e=>setCriteria({...criteria,transmission:e.target.value})}><option value="">Any transmission</option><option>Manual</option><option>Automatic</option></select></label><label>Derivative<select value={family} onChange={e=>setCriteria({...criteria,derivative:e.target.value==='custom'?' ':groups.find(g=>g.label===e.target.value)?.variants.join(',')??''})}><option value="">Any derivative</option>{groups.map(g=><option key={g.label} value={g.label}>{g.label}</option>)}<option value="custom">Enter exact variant…</option></select></label>{family==='custom'&&<label>Exact variant<input maxLength={160} placeholder="As named in the advert" value={criteria.derivative.trimStart()} onChange={e=>setCriteria({...criteria,derivative:e.target.value||' '})}/></label>}<p className="muted small">Suggestions are available before searching. Variant naming varies; our catalogue may not cover every designation.</p>{([{field:'minYear',label:'Year from',min:1900,max:2100},{field:'maxYear',label:'Year to',min:1900,max:2100},{field:'maxPrice',label:'Maximum price (£)',min:0},{field:'maxMileage',label:'Maximum mileage',min:0}] as const).map(f=><label key={f.field}>{f.label}<input type="number" min={f.min} max={'max' in f?f.max:undefined} step="1" placeholder="Any" value={criteria[f.field]} onChange={e=>setCriteria({...criteria,[f.field]:e.target.value})}/></label>)}<div id="search-preferences"><PreferenceEditor make={criteria.make} model={criteria.model} value={preferences} onChange={setPreferences}/></div><button className="button dark" disabled={disabled||!criteria.model.trim()}>{busy?'Working…':'Search · reserve 2p'}</button></form>
 <details className="live-help"><summary>How live search works</summary><p className="muted small">Changing criteria is free. Each search returns up to 50 listings. Search, loading another batch and opening details each reserve 2p. Derivative suggestions use a local catalogue of exact variant names; coverage is not exhaustive. Generation filtering is not yet available. Equipment evidence is analysed when details are opened, without another request. The local allowance is not an account-wide billing cap.</p></details></aside><section className="live-results" aria-label="Live car results">
 {error&&<p className="notice" role="alert">{error}</p>}
 {submitted?<><div className="results-heading"><h2>{submitted.make} {submitted.model} · {cars.length} eligible cars · batch {page+1}</h2><span>{total??'Unknown'} provider results before eligibility checks</span></div><p className="muted small">Applied: {[submitted.transmission,searchDerivatives(submitted.make,submitted.model).find(g=>g.variants.join(',')===submitted.derivative)?.label||submitted.derivative,submitted.minYear&&`From ${submitted.minYear}`,submitted.maxYear&&`To ${submitted.maxYear}`,submitted.maxPrice&&`Up to £${submitted.maxPrice}`,submitted.maxMileage&&`Up to ${submitted.maxMileage} miles`].filter(Boolean).join(' · ')||'No additional limits'}</p><div className="car-grid">{cars.map(car=><article className="car-card" key={car.id}><LivePhoto car={car}/><div className="card-content"><p className="card-meta">{car.year??'Year unknown'} · {car.transmission||'Unknown'} · {car.location}</p><h3>{car.make} {car.model}<span>{car.trim}</span></h3><p className="card-price"><strong>{pounds(car.price)}</strong><span>{car.mileage?.toLocaleString('en-GB')??'Unknown'} miles</span></p><p className="muted small">{car.daysOnMarket??'Unknown'} days on market · {car.seller}</p><p className="muted small">Specification not checked{preferences.length?` · ${preferences.length} preferences to check`:''}</p><button className="button" disabled={disabled} onClick={()=>void run('detail',{id:car.id})}>Open details · reserve 2p</button></div></article>)}</div>{!cars.length&&<p>No eligible cars in this batch. A new search or batch is another request.</p>}<div className="live-pagination"><button className="button" disabled={disabled||page===0} onClick={()=>void run('search',{...submitted,page:page-1})}>Previous 50 · another request · 2p</button><button className="button" disabled={disabled||page>=10||total===null||(page+1)*LIVE_PAGE_SIZE>=total} onClick={()=>void run('search',{...submitted,page:page+1})}>Load next 50 · another request · 2p</button></div></>:<div className="empty live-welcome"><p className="eyebrow">START YOUR SEARCH</p><h2>Your next car is out there.</h2><p>Choose a make and model, then search when you’re ready.</p><p className="muted small">Try Porsche 911. One search and one detail view reserve 4p.</p><a className="text-button" href="/detail-demo">Preview a fictional car detail · no API calls ↗</a></div>}
 </section></div></main>;
}
function LivePhoto({car}:{car:Listing}){const [failed,setFailed]=useState(false);return car.photo&&!failed?<img className="live-photo" src={car.photo} alt={`${car.make} ${car.model} — dealer photograph`} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(true)}/>:<div className="live-photo missing">Photograph unavailable</div>;}
