import {useId,useState} from 'react';
import {preferenceGroups,preferenceSuggestions,addPreference,type EquipmentPreference,type PreferencePriority} from '../shared/preferences';
export function PreferenceEditor({make,model='',value,onChange}:{make:string;model?:string;value:EquipmentPreference[];onChange:(next:EquipmentPreference[])=>void}){
 const [custom,setCustom]=useState('');const [priority,setPriority]=useState<PreferencePriority>('nice');const id=useId();
 const suggestions=preferenceSuggestions(make,model);
 const toggle=(label:string)=>onChange(value.some(p=>p.label===label)?value.filter(p=>p.label!==label):addPreference(value,label));
 function addCustom(){onChange(addPreference(value,custom,priority));setCustom('');}
 return <section className="preference-editor" aria-labelledby={id}>
  <h3 id={id}>What you’re looking for</h3><p className="muted small">Your wish list, not fitted equipment. Must-haves are flagged for checking; missing information won’t hide cars.</p>
  {Object.entries(preferenceGroups).map(([group,labels])=><details key={group} className="preference-group"><summary>{group}<span>{labels.filter(label=>value.some(p=>p.label===label)).length||'+'}</span></summary><div>{labels.map(label=><label key={label}><input type="checkbox" checked={value.some(p=>p.label===label)} disabled={value.length>=20&&!value.some(p=>p.label===label)} onChange={()=>toggle(label)}/>{label}</label>)}</div></details>)}
  {!!suggestions.length&&<details className="preference-group"><summary>Suggestions for {make}<span>+</span></summary><p className="muted small">Names to look for. Availability varies by model and year.</p><div>{suggestions.map(label=><label key={label}><input type="checkbox" checked={value.some(p=>p.label===label)} disabled={value.length>=20&&!value.some(p=>p.label===label)} onChange={()=>toggle(label)}/>{label}</label>)}</div></details>}
  <div className="custom-preference"><label>Anything specific?<input maxLength={80} placeholder="e.g. front axle lift" value={custom} onChange={e=>setCustom(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addCustom();}}}/></label><label>Priority for this option<select value={priority} onChange={e=>setPriority(e.target.value as PreferencePriority)}><option value="nice">Nice-to-have</option><option value="must">Must-have</option></select></label><button type="button" className="button" disabled={!custom.trim()||value.length>=20} onClick={addCustom}>Add preference</button><p className="muted small">Custom options match the words you enter. Up to 20 preferences.</p></div>
  {!!value.length&&<div className="selected-preferences"><h4>Your priorities</h4>{value.map(p=><div key={p.label} className="preference-priority"><span>{p.label}</span><select aria-label={`${p.label} priority`} value={p.priority} onChange={e=>onChange(value.map(v=>v.label===p.label?{...v,priority:e.target.value as PreferencePriority}:v))}><option value="nice">Nice-to-have</option><option value="must">Must-have</option></select><button type="button" className="text-button" aria-label={`Remove ${p.label}`} onClick={()=>onChange(value.filter(v=>v.label!==p.label))}>Remove</button></div>)}</div>}
 </section>;
}
